# Generated by Django 4.2.4 on 2024-04-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_drink_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
